CREATE TABLE IF NOT EXISTS hardware (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS software (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
price REAL NOT NULL
);